import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import Head from "next/head";
import { Header } from "~/layouts/header";

const MyApp: AppType<{ session: Session | null }> = ({
    Component,
    pageProps: { session, ...pageProps },
    }) => {
    return (
    <SessionProvider session={session}>
        <Head>
            <title>NextShop</title>
            <meta name="e-commerce web-site" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <Component {...pageProps} />
    </SessionProvider>
    );
    };

    export default api.withTRPC(MyApp);
